//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRPO_PR13_Cherednichenko402.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ISRPO13Cher402Entities : DbContext
    {
        private static ISRPO13Cher402Entities _context;
        
        public ISRPO13Cher402Entities()
            : base("name=ISRPO13Cher402Entities")
        {
        }
    
        public static ISRPO13Cher402Entities GetContext()
        {
            if (_context == null)
                _context = new ISRPO13Cher402Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<Strana> Strana { get; set; }
    }
}
